### ISSUE TITLE
leveldown-hyper branch seem's uninstallable

### ISSUE THREAD

**Issue by ekristen** [rvagg/node-leveldown#149]
I'm attempting to use liveBackup, but it is undefined when I installed `level-hyper`, I found the `leveldown-hyper` branch and the reference to the `liveBackup` code there, I attempted to install this branch directly but it errors out.

```
make: *** No rule to make target `Release/obj.target/leveldb/deps/leveldb/leveldb-hyper/util/bloom.o', needed by `Release/leveldb.a'.  Stop.
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Darwin 14.1.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd ~/project/node_modules/leveldown-hyper
gyp ERR! node -v v0.10.36
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok
npm ERR! Darwin 14.1.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "git://github.com/rvagg/node-leveldown.git#hyper-leveldb"
npm ERR! node v0.10.36
npm ERR! npm  v2.4.1
npm ERR! code ELIFECYCLE
```

**Comment by hij1nx** [comment]
Using a regular install of `level-hyper`, I think you can access the method from `db.db.liveBackup()`.

**Comment by ralphtheninja** [comment]
@ekristen I think we resolved this, right? Closing.
